### PR TITLE
fix is_stdlib() for nightly and enable nightly tests

### LINKED ISSUE #1872: Stdlib packages marked as not found
Stdlib packages are indicated as not found in the registry, but they execute correctly.

There's also a LocalRegistry in use, if that matters.

image

Pluto v0.17.7, Julia 1.8-DEV

### PR DESCRIPTION
**Pull request by Pangoraw**
fixes #1872

### CODE REVIEW

File: src/packages/PkgCompat.jl [hunk 1]
```diff
@@ -215,7 +215,14 @@ end
 
 # (⚠️ Internal API with fallback)
 _stdlibs() = try
-	values(Pkg.Types.stdlibs())
+	stdlibs = values(Pkg.Types.stdlibs())
+	stdlibs = if VERSION > v"1.8.0-"
```
Comment (fonsp) [inline src/packages/PkgCompat.jl:219]: Can you replace this with a feature check? e.g.

```julia
if eltype(stdlibs) == String
	stdlibs
elseif eltype(stdlibs)
	first.(stdlibs)
else
	error("Failed to get stdlibs")
end
```
